### ISSUE TITLE
地点-时间轴视图上的人员移动轨迹的聚类 

### ISSUE THREAD

**Issue by McFateWang** [AgeBing/chinavis-2019-challange#6]
# 图例
![image](https://user-images.githubusercontent.com/36266942/56561542-ff79ed00-65d9-11e9-9ca6-168a020c7417.png)

# 建立视图
1. 时间轴上：三天连续绘制；人员的休息时段用较短的灰色斜线示意
2. 地点轴上：题目中有十多个房间，除了主会场、各个分会场、食堂、休息室外，还要放置哪些地点？（入口&出口，厕所，走廊，签到处......）
3. 图中每个人员的轨迹是固定不变的，不随着分类改变

# 轨迹聚类
1.  暂定是按照房间类别做聚类，人员都在主会场和都在分会场A的权重不同（都在分会场A更能区分出来）
2. 某些异常轨迹要排除，传感器的定位不准、穿墙，要修正

**Comment by AgeBing** [comment]
( **供参考** ) 

![屏幕快照 2019-04-23 下午3 08 11](https://user-images.githubusercontent.com/20612403/56561416-af028f80-65d9-11e9-9c0b-d30c9dea79ed.png)

- https://bizcharts.net/products/bizCharts/demo/detail?id=relation-sankey&selectedKey=%E5%85%B3%E7%B3%BB%E5%9B%BE
- https://geekplux.com/2018/08/28/how-to-implement-sankey-diagram

**Comment by McFateWang** [comment]
![image](https://user-images.githubusercontent.com/36266942/57190317-65a42f80-6f4b-11e9-8bf8-8944b1661792.png)

**Comment by McFateWang** [comment]
# 筛选的条件
- 得到轨迹的相似度后，采用哪种聚类算法来对人员分类（目前是k-means）
- 对时间进行zoom in 对应之前版本的time line
